//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchPay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public decimal CardID { get; set; }
        public string ProfileNumber { get; set; }
        public byte CardType { get; set; }
        public byte TravelType { get; set; }
        public string CardDescription { get; set; }
        public string CardCompany { get; set; }
        public decimal CCID { get; set; }
        public string CardNumber { get; set; }
        public string CardHolder { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public bool DefaultCard { get; set; }
    }
}
