//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchPay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCBatchUpload
    {
        public decimal InvoiceDetailID { get; set; }
        public decimal InvoiceID { get; set; }
        public byte TransactionType { get; set; }
        public decimal GrossAmount { get; set; }
        public string CCMask { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> CCID { get; set; }
        public string Reference { get; set; }
        public string CardHolder { get; set; }
        public string AuthorizationNumber { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string InvoiceNumber { get; set; }
        public string IndiCardNo { get; set; }
        public string ProfileNumber { get; set; }
        public string CorpCardNo { get; set; }
        public string ProfileName { get; set; }
        public string PassengerName { get; set; }
        public string CurrencyCode { get; set; }
        public string CardNumber { get; set; }
        public string CorpCardHolder { get; set; }
        public Nullable<System.DateTime> CorpCardExp { get; set; }
    }
}
