//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchPay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCEncrypted
    {
        public decimal CCID { get; set; }
        public string CCMask { get; set; }
        public byte[] CCNumber { get; set; }
    }
}
