//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchPay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> ExtractedDate { get; set; }
        public Nullable<System.Guid> ExtractedBy { get; set; }
    }
}
