//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchPay.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravComEntities : DbContext
    {
        public TravComEntities()
            : base("name=TravComEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<ARInvoiceDetails> ARInvoiceDetails { get; set; }
        public virtual DbSet<ARInvoices> ARInvoices { get; set; }
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<CCEncrypted> CCEncrypted { get; set; }
        public virtual DbSet<CCBatchUploadHash> CCBatchUploadHash { get; set; }
        public virtual DbSet<CCBatchUpload> CCBatchUpload { get; set; }
    }
}
